### ISSUE TITLE
Special character is not Parsing. . .Can any one Help me ?

### ISSUE THREAD

**Issue by NikunjGodhani** [tadija/AEXML#107]
When i am trying to parsing "&" special character than i am getting the error in Xcode 7.3.1 

Error is given below . . .

I was used AEXML. . . 

ptional(System.ArgumentException: Unterminated string passed in. (67): [{&quot;app_List&quot;:[{&quot;server_id&quot;:&quot;33536&quot;,&quot;reason&quot;:&quot;Pull&quot;,&quot;note&quot;:&quot;Dodo did

   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeString()

   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)

   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeDictionary(Int32 depth)

   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)

   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeList(Int32 depth)

   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)

   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeDictionary(Int32 depth)

   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)

   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeList(Int32 depth)

   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)

   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.BasicDeserialize(String input, Int32 depthLimit, JavaScriptSerializer serializer)

**Comment by tadija** [comment]
Hi,

I don't understand the problem with given information, also AEXML requires Xcode 8+ as far as I know, so I'll just close this one.
